// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtoh6mUuuW88vcgFEHI8DF6DxbXUYEwII',
    appId: '1:1084624498357:web:d3e2147020e4f4942b18fc',
    messagingSenderId: '1084624498357',
    projectId: 'budget-tracker-258e2',
    authDomain: 'budget-tracker-258e2.firebaseapp.com',
    storageBucket: 'budget-tracker-258e2.firebasestorage.app',
    measurementId: 'G-7K4Q7SNBN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMx16JB2VN1fVP8oi82LqdmK71N1yG20k',
    appId: '1:1084624498357:android:b6059cc310753f902b18fc',
    messagingSenderId: '1084624498357',
    projectId: 'budget-tracker-258e2',
    storageBucket: 'budget-tracker-258e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQxiaMVAUXgvtxmckmbdgqcXqy7aiTEkQ',
    appId: '1:1084624498357:ios:eca8f7ae61ff685d2b18fc',
    messagingSenderId: '1084624498357',
    projectId: 'budget-tracker-258e2',
    storageBucket: 'budget-tracker-258e2.firebasestorage.app',
    iosBundleId: 'com.example.budgetTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQxiaMVAUXgvtxmckmbdgqcXqy7aiTEkQ',
    appId: '1:1084624498357:ios:eca8f7ae61ff685d2b18fc',
    messagingSenderId: '1084624498357',
    projectId: 'budget-tracker-258e2',
    storageBucket: 'budget-tracker-258e2.firebasestorage.app',
    iosBundleId: 'com.example.budgetTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtoh6mUuuW88vcgFEHI8DF6DxbXUYEwII',
    appId: '1:1084624498357:web:db7af6945cebcb8f2b18fc',
    messagingSenderId: '1084624498357',
    projectId: 'budget-tracker-258e2',
    authDomain: 'budget-tracker-258e2.firebaseapp.com',
    storageBucket: 'budget-tracker-258e2.firebasestorage.app',
    measurementId: 'G-1PNP9NKSDT',
  );
}
